const crypto = require('crypto');

const RENTAL_DATA = {
  irvine: { name: 'Irvine 尔湾', '1bd': [2300, 2800], '2bd': [3000, 3800], '3bd': [3800, 5000], sfr: [5500, 8000] },
  'los-angeles': { name: 'Los Angeles 洛杉矶', '1bd': [2000, 2600], '2bd': [2500, 3500], '3bd': [3500, 5000], sfr: [5000, 8500] },
  arcadia: { name: 'Arcadia 阿凯迪亚', '1bd': [1800, 2200], '2bd': [2500, 3200], '3bd': [3200, 4200], sfr: [4500, 6500] },
  pasadena: { name: 'Pasadena 帕萨迪纳', '1bd': [2200, 2800], '2bd': [2700, 3500], '3bd': [3600, 4800], sfr: [5200, 7500] },
  'san-gabriel': { name: 'San Gabriel 圣盖博', '1bd': [1800, 2300], '2bd': [2300, 3000], '3bd': [3000, 4200], sfr: [4200, 6200] },
  'rowland-heights': { name: 'Rowland Heights 罗兰岗', '1bd': [1600, 2000], '2bd': [2200, 2800], '3bd': [2800, 3600], sfr: [3800, 5000] },
  'diamond-bar': { name: 'Diamond Bar 钻石吧', '1bd': [1700, 2100], '2bd': [2300, 2900], '3bd': [2900, 3800], sfr: [4000, 5500] },
  'chino-hills': { name: 'Chino Hills 奇诺岗', '1bd': [1800, 2200], '2bd': [2400, 3000], '3bd': [3000, 3900], sfr: [4200, 5800] },
  riverside: { name: 'Riverside 河滨市', '1bd': [1400, 1800], '2bd': [1900, 2400], '3bd': [2400, 3200], sfr: [3200, 4500] }
};

const PROPERTY_TYPE_LABELS = {
  '1bd': '1BD / 1BA',
  '2bd': '2BD / 2BA',
  '3bd': '3BD / 2BA',
  sfr: 'Single Family Home'
};

const TYPICAL_SQFT = {
  '1bd': 750,
  '2bd': 1050,
  '3bd': 1450,
  sfr: 2200
};

function sendJson(res, statusCode, payload) {
  res.statusCode = statusCode;
  res.setHeader('Content-Type', 'application/json; charset=utf-8');
  res.end(JSON.stringify(payload));
}

function getClientMeta(req) {
  return {
    ip: req.headers['x-forwarded-for'] || req.socket.remoteAddress || '',
    userAgent: req.headers['user-agent'] || ''
  };
}

function sanitizeString(value, maxLength = 2000) {
  if (value === undefined || value === null) return '';
  return String(value).trim().slice(0, maxLength);
}

function clamp(value, min, max) {
  return Math.min(Math.max(value, min), max);
}

function roundToNearest50(value) {
  return Math.round(value / 50) * 50;
}

function createEstimate(input, req) {
  const cityKey = sanitizeString(input.city, 80);
  const propertyType = sanitizeString(input.propertyType, 20);
  const areaSqft = Number(input.areaSqft);
  const city = RENTAL_DATA[cityKey];

  if (!city || !city[propertyType] || !Number.isFinite(areaSqft) || areaSqft < 300 || areaSqft > 10000) {
    const error = new Error('Invalid rental estimate input');
    error.statusCode = 400;
    throw error;
  }

  const baseRange = city[propertyType];
  const areaFactor = clamp(Math.sqrt(areaSqft / TYPICAL_SQFT[propertyType]), 0.8, 1.25);
  const minRent = roundToNearest50(baseRange[0] * areaFactor);
  const maxRent = roundToNearest50(baseRange[1] * areaFactor);

  return {
    id: crypto.randomUUID(),
    createdAt: new Date().toISOString(),
    ...getClientMeta(req),
    cityKey,
    cityName: city.name,
    propertyType,
    propertyTypeLabel: PROPERTY_TYPE_LABELS[propertyType],
    areaSqft,
    minRent,
    maxRent,
    displayRange: `$${minRent.toLocaleString()} - $${maxRent.toLocaleString()}/mo`
  };
}

function sanitizeInquiry(input, req) {
  return {
    id: crypto.randomUUID(),
    createdAt: new Date().toISOString(),
    ...getClientMeta(req),
    source: sanitizeString(input.source, 80),
    name: sanitizeString(input.name, 120),
    phone: sanitizeString(input.phone, 80),
    email: sanitizeString(input.email, 160),
    serviceNeeded: sanitizeString(input.serviceNeeded, 200),
    city: sanitizeString(input.city, 160),
    notes: sanitizeString(input.notes, 2000),
    propertyType: sanitizeString(input.propertyType, 120),
    areaSqft: sanitizeString(input.areaSqft, 40),
    estimatedRent: sanitizeString(input.estimatedRent, 120),
    estimateId: sanitizeString(input.estimateId, 120),
    page: sanitizeString(input.page, 300)
  };
}

function getGithubRepoConfig() {
  const repo = process.env.GITHUB_DATA_REPO;
  const token = process.env.GITHUB_TOKEN;

  if (!repo || !token) {
    const error = new Error('Missing GitHub storage configuration');
    error.statusCode = 500;
    throw error;
  }

  return { repo, token };
}

function getRecordKind(filePath) {
  return filePath.includes('rental-estimates') ? 'rental-estimate' : 'inquiry';
}

async function createGithubRecord(recordKind, record) {
  const { repo, token } = getGithubRepoConfig();
  const titleName = record.name || record.cityName || record.city || 'New record';
  const title = `[rentalinca:${recordKind}] ${titleName}`;
  const body = [
    'Private backend record generated by rentalinca.com.',
    '',
    '```json',
    JSON.stringify(record, null, 2),
    '```'
  ].join('\n');

  const response = await fetch(`https://api.github.com/repos/${repo}/issues`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github+json',
      'Content-Type': 'application/json',
      'User-Agent': 'rentalinca-api'
    },
    body: JSON.stringify({ title, body })
  });

  if (!response.ok) {
    const error = new Error(`GitHub issue write failed: ${response.status}`);
    error.statusCode = 502;
    throw error;
  }
}

function parseRecordFromIssue(issue) {
  const match = String(issue.body || '').match(/```json\s*([\s\S]*?)\s*```/);
  if (!match) return null;
  try {
    return JSON.parse(match[1]);
  } catch {
    return null;
  }
}

async function readGithubJson(filePath) {
  const { repo, token } = getGithubRepoConfig();
  const recordKind = getRecordKind(filePath);
  const url = new URL(`https://api.github.com/repos/${repo}/issues`);
  url.searchParams.set('state', 'all');
  url.searchParams.set('per_page', '100');

  const response = await fetch(url, {
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github+json',
      'User-Agent': 'rentalinca-api'
    }
  });

  if (!response.ok) {
    const error = new Error(`GitHub issue read failed: ${response.status}`);
    error.statusCode = 502;
    throw error;
  }

  const issues = await response.json();
  const data = issues
    .filter(issue => String(issue.title || '').startsWith(`[rentalinca:${recordKind}]`))
    .map(parseRecordFromIssue)
    .filter(Boolean);
  return { data, sha: null };
}

async function prependGithubRecord(filePath, record, message) {
  await createGithubRecord(getRecordKind(filePath), record, message);
}

function formatTelegramRecord(recordKind, record) {
  if (recordKind === 'rental-estimate') {
    return [
      '🏠 New Rental Estimate',
      `City: ${record.cityName || record.cityKey || ''}`,
      `Type: ${record.propertyTypeLabel || record.propertyType || ''}`,
      `Area: ${record.areaSqft || ''} sqft`,
      `Range: ${record.displayRange || ''}`,
      `Time: ${record.createdAt || ''}`
    ].join('\n');
  }

  return [
    '📋 New Inquiry',
    `Name: ${record.name || ''}`,
    `Phone: ${record.phone || ''}`,
    `Email: ${record.email || ''}`,
    `Service: ${record.serviceNeeded || record.source || ''}`,
    `City: ${record.city || ''}`,
    `Type/Area: ${[record.propertyType, record.areaSqft ? `${record.areaSqft} sqft` : ''].filter(Boolean).join(' / ')}`,
    `Estimate: ${record.estimatedRent || ''}`,
    `Notes: ${record.notes || ''}`,
    `Time: ${record.createdAt || ''}`
  ].join('\n');
}

async function sendResendAutoReply(inquiry) {
  const apiKey = String(process.env.RESEND_API_KEY || '').trim();
  if (!apiKey || !inquiry.email || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(inquiry.email)) return;

  const from = String(process.env.RESEND_FROM || 'onboarding@resend.dev').trim();
  const name = inquiry.name || '您'
  const service = inquiry.serviceNeeded || '物业管理咨询'
  const city = inquiry.city ? ` · ${inquiry.city}` : ''

  const html = `<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="utf-8"/>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
</head>
<body style="margin:0;padding:0;background:#f5f5f0;font-family:'Helvetica Neue',Arial,sans-serif;">
<table width="100%" cellpadding="0" cellspacing="0" style="background:#f5f5f0;padding:32px 0;">
  <tr><td align="center">
    <table width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;background:#fff;border-radius:4px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,.06);">
      <tr>
        <td style="background:#1c2b1a;padding:28px 40px;text-align:center;">
          <p style="margin:0;color:#a8c49a;font-size:13px;letter-spacing:.3em;text-transform:uppercase;font-weight:500;">RentalInCA</p>
          <p style="margin:4px 0 0;color:#888;font-size:11px;letter-spacing:.15em;">南加州华人物业管理 · David Dai</p>
        </td>
      </tr>
      <tr>
        <td style="padding:40px;">
          <p style="margin:0 0 4px;color:#999;font-size:12px;letter-spacing:.2em;text-transform:uppercase;">咨询确认</p>
          <h1 style="margin:0 0 24px;font-size:22px;font-weight:400;color:#1c2b1a;">已收到您的物业咨询</h1>
          <p style="margin:0 0 16px;color:#444;font-size:15px;line-height:1.8;">${name} 您好，</p>
          <p style="margin:0 0 20px;color:#666;font-size:14px;line-height:1.8;">
            我已收到您关于 <strong>${service}${city}</strong> 的咨询，将在 1 个工作日内与您联系。
          </p>
          <table cellpadding="0" cellspacing="0" style="width:100%;background:#f8faf7;border:1px solid #e0e8de;border-radius:3px;margin-bottom:24px;">
            <tr><td style="padding:12px 20px;border-bottom:1px solid #e0e8de;">
              <span style="color:#999;font-size:12px;letter-spacing:.1em;text-transform:uppercase;margin-right:12px;">服务类型</span>
              <span style="color:#333;font-size:14px;">${service}</span>
            </td></tr>
            ${inquiry.city ? `<tr><td style="padding:12px 20px;border-bottom:1px solid #e0e8de;">
              <span style="color:#999;font-size:12px;letter-spacing:.1em;text-transform:uppercase;margin-right:12px;">城市</span>
              <span style="color:#333;font-size:14px;">${inquiry.city}</span>
            </td></tr>` : ''}
            <tr><td style="padding:12px 20px;">
              <span style="color:#999;font-size:12px;letter-spacing:.1em;text-transform:uppercase;margin-right:12px;">联系电话</span>
              <span style="color:#333;font-size:14px;">${inquiry.phone || '未填写'}</span>
            </td></tr>
          </table>
          <p style="margin:0 0 16px;color:#666;font-size:14px;line-height:1.8;">
            如需更快响应，欢迎直接微信联系 David，DRE# 02202763。
          </p>
          <p style="margin:24px 0 0;text-align:center;">
            <a href="https://rentalinca.com/contact.html" style="display:inline-block;background:#1c2b1a;color:#fff;text-decoration:none;font-size:12px;letter-spacing:.2em;padding:12px 32px;text-transform:uppercase;">访问 RentalInCA</a>
          </p>
        </td>
      </tr>
      <tr>
        <td style="background:#f8faf7;padding:20px 40px;text-align:center;border-top:1px solid #e0e8de;">
          <p style="margin:0;color:#999;font-size:11px;line-height:1.6;">
            此邮件由 <a href="https://rentalinca.com" style="color:#a8c49a;text-decoration:none;">rentalinca.com</a> 自动发送。
            David Dai · DRE# 02202763 · Universal Elite Realty
          </p>
        </td>
      </tr>
    </table>
  </td></tr>
</table>
</body>
</html>`

  await fetch('https://api.resend.com/emails', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${apiKey}`,
      'Content-Type': 'application/json; charset=utf-8',
    },
    body: JSON.stringify({
      from,
      to: inquiry.email,
      subject: `已收到您的物业管理咨询 | RentalInCA`,
      html,
    }),
  })
}

async function sendTelegramNotification(recordKind, record) {
  const botToken = String(process.env.TELEGRAM_BOT_TOKEN || '').trim();
  const chatId = String(process.env.TELEGRAM_CHAT_ID || '').trim();
  if (!botToken || !chatId) return;

  const response = await fetch(`https://api.telegram.org/bot${botToken}/sendMessage`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      chat_id: chatId,
      text: formatTelegramRecord(recordKind, record),
      disable_web_page_preview: true
    })
  });

  if (!response.ok) {
    console.error(`Telegram notification failed: ${response.status}`);
  }
}

module.exports = {
  createEstimate,
  prependGithubRecord,
  readGithubJson,
  sendTelegramNotification,
  sendResendAutoReply,
  sanitizeInquiry,
  sendJson
};
